apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Values.namespace }}
data:
  DJANGO_DEBUG: "{{ .Values.configmap.DJANGO_DEBUG }}"
  DJANGO_ALLOWED_HOSTS: "{{ .Values.configmap.DJANGO_ALLOWED_HOSTS }}"
  DJANGO_CSRF_TRUSTED_ORIGINS: "{{ .Values.configmap.DJANGO_CSRF_TRUSTED_ORIGINS }}"
  DJANGO_SECURE: "{{ .Values.configmap.DJANGO_SECURE }}"
  DJANGO_HSTS_SECONDS: "{{ .Values.configmap.DJANGO_HSTS_SECONDS }}"
  DJANGO_EMAIL_BACKEND: "{{ .Values.configmap.DJANGO_EMAIL_BACKEND }}"
  USE_S3: "{{ .Values.configmap.USE_S3 }}"
  AWS_BUCKET_NAME: "{{ .Values.configmap.AWS_BUCKET_NAME }}"
  AWS_S3_REGION_NAME: "{{ .Values.configmap.AWS_S3_REGION_NAME }}"
  AWS_S3_CUSTOM_DOMAIN: "{{ .Values.configmap.AWS_S3_CUSTOM_DOMAIN }}"
