apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  DJANGO_SECRET_KEY: {{ .Values.secret.DJANGO_SECRET_KEY | b64enc | quote }}
  DATABASE_URL: {{ .Values.secret.DATABASE_URL | b64enc | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.secret.AWS_ACCESS_KEY_ID | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secret.AWS_SECRET_ACCESS_KEY | b64enc | quote }}
  