apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.service.app }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.service.app }}
  ports:
    - protocol: {{ .Values.service.port.protocol }}
      port: {{ .Values.service.port.port }}
      targetPort: {{ .Values.service.port.targetPort }}
