apiVersion: v1
kind: Secret
metadata:
  name: puddle-app-secret
  namespace: puddle-app-namespace
data:
  DJANGO_SECRET_KEY: bWF2ODkwajMsbWMwYy1jeDJ2N3k3OGtqbjc4bDA3LWN4Mi0rY3ViNCs3dTQ2LTI1Yw==
  DATABASE_URL: ""