apiVersion: v1
kind: Service
metadata:
  name: puddle-app-service
  namespace: puddle-app-namespace
  labels:
    app: puddle-app
spec:
  type: LoadBalancer
  selector:
    app: puddle-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000